# Generated by Django 4.1.5 on 2023-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfeature',
            name='special_features',
            field=models.TextField(blank=True),
        ),
    ]
