# Generated by Django 4.1.5 on 2023-02-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='joinus.board_feature'),
        ),
    ]
