# Generated by Django 4.1.5 on 2023-02-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0002_alter_boardfeature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfeature',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
