# Generated by Django 4.1.5 on 2023-02-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0002_alter_review_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
    ]
