# Generated by Django 4.1.5 on 2023-01-21 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joinus', '0003_alter_board_feature_author_alter_review_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post',
        ),
        migrations.AddField(
            model_name='review',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='joinus.board_feature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board_feature',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_feature', to=settings.AUTH_USER_MODEL),
        ),
    ]
