# Generated by Django 4.1.5 on 2023-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0003_alter_boardfeature_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
