# Generated by Django 4.1.5 on 2023-01-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0004_remove_review_post_review_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_feature',
            name='microprocessor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='board_feature',
            name='excerpt',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
