# Generated by Django 4.1.5 on 2023-01-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0005_board_feature_microprocessor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='joinus.board_feature'),
        ),
    ]
