# Generated by Django 4.1.5 on 2023-01-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0006_alter_review_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_feature',
            name='special_features',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
