# Generated by Django 4.1.5 on 2023-02-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0009_alter_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_feature',
            name='avg_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board_feature',
            name='avg_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
