# Generated by Django 4.1.5 on 2023-02-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0010_remove_board_feature_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='joinus.board_feature'),
            preserve_default=False,
        ),
    ]
